git:
  depth: 1

matrix:
  include:

    - os: linux
      language: cpp
      sudo: false
      addons:
        apt:
          packages:
            - qttools5-dev
    #powerjob
    - os: linux
      arch: ppc64le
      language: cpp
      sudo: false
      addons:
        apt:
          packages:
            - qttools5-dev           
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        
